server {
    listen 8080;
    server_name _;
    root /var/www/trading-journal;
    index index.html;

    location /trading/ {
        proxy_pass http://localhost:1880/trading/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
